library(dplyr)
mpg_db = read.csv('MechaCar_mpg.csv')
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,mpg_db))
AWD_db = filter(mpg_db, AWD == 1)
nAWD_db = filter(mpg_db, AWD == 0)
mpgAWD = subset(mpg_db, AWD == 1, select = mpg)
mpgnAWD = subset(mpg_db, AWD == 0, select = mpg)
t.test(mpgAWD, mpgnAWD, alternative = "two.sided", var.equal = FALSE)
temp <- as.numeric(unlist(mpgAWD))
shapiro.test(temp)
temp2 <- as.numeric(unlist(mpgnAWD))
shapiro.test(temp2)
